FROM ic-harbor.baozun.com/ic/alpine-node10:v1.1

RUN mkdir /opt/project -p
WORKDIR /opt/project
ADD  .nuxt /opt/project/.nuxt

ADD package.json /opt/project


RUN  yarn config set @baozun:registry http://npm.baozun.com:7001 

RUN yarn config set registry https://registry.npm.taobao.org

RUN yarn global add mirror-config-china

RUN yarn

# && cd staff \
# && yarn config set registry https://registry.npm.taobao.org \
# && yarn \
# && npm run publish API_ENV=sit \
# && npm run alioss API_ENV=sit \
# && cd /opt/project/resource/sites/88000204/latest/ \
# && yarn --prod
EXPOSE 3000

RUN chown -R vmuser. /opt
USER vmuser

CMD ["yarn", "start"]

