FROM ic-harbor.baozun.com/ic/alpine-node10:v1.1


RUN mkdir /opt/project -p
WORKDIR /opt/project
ADD  ./ /opt/project

RUN  yarn config set @baozun:registry http://npm.baozun.com:7001 \
  && yarn config set registry https://registry.npm.taobao.org \
  && yarn global add mirror-config-china \
  && yarn \
  && cd staff \
  && yarn config set registry https://registry.npm.taobao.org \
  && yarn \
  && npm run publish API_ENV=uat \
  && npm run alioss API_ENV=uat \
  && cd /opt/project/resource/sites/88000204/latest/ \
  && yarn --prod
EXPOSE 8080

RUN chown -R vmuser. /opt
USER vmuser

WORKDIR  /opt/project

CMD ["npm", "run", "start:uat"]

