FROM nginx:1.10.3

RUN mkdir -p /var/www/brembo-front && mkdir -p /app && mkdir -p /logs && rm -f /etc/nginx/conf.d/*
COPY dist /var/www/brembo-front
COPY ./docker/nginx/gca-* /etc/nginx/
COPY ./docker/nginx/* /etc/nginx/conf.d/
COPY ./docker/entrypoint.sh /app/

EXPOSE 80
EXPOSE 443

ENTRYPOINT /bin/bash -c "exec /app/entrypoint.sh"