query getProductList{
  shop{
    name
    products{
      pageInfo{
        startCursor
        endCursor
        totalCount
        hasNextPage
        hasPreviousPage
      }
      edges{
        node{
          code
          title
        }
        cursor
      }
      minPrice{
        amount
        currencyCode
      }
      maxPrice{
        amount
        currencyCode
      }
      options{
        code
        name
        attributeType
        values{
          key
          value
          frontName
          imageUrl
          total
        }
      }
    }
  }
}